version: "3.8"
services:
  waslak_app:
    container_name: waslak_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    networks:
      - app_network
  waslak_nginx:
    container_name: waslak_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./public:/usr/src/app/public
    ports:
      - "8080:80"
    depends_on:
      - waslak_app
    environment:
      NGINX_FPM_HOST: waslak_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network
  waslak_db:
    container_name: waslak_db
    image: mysql:8.0.20
    platform: linux/x86_64
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: waslak
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app_network
  waslak_mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: waslak_mailhog
    restart: unless-stopped
    networks:
      - app_network
    ports:
      - "8025:8025"
    expose:
      - 1025
      - 8025

networks:
  app_network:
    driver: bridge
